x=int(input("Enter Value of X = "))
y=int(input("Enter Value of Y = "))
print("X==Y =",x==y)
print("X!=Y =",x!=y)
print("X>Y =",x>y)
print("X<Y =",x<y)
print("X>=Y =",x>=y)
print("X<=Y =",x<=y)
